import './globals.css'
import Providers from "./Providers";
import Header from "../components/Header";
import NavBar from "@/components/NavBar";

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">



      <body>
      <Providers>
          {/* Header */}
          <Header />
          {/* NavBar */}
          <NavBar />

          {children}
      </Providers>


      </body>

    </html>
  )
}
